### PR TITLE
[Yang] Add TUNNEL_TERM field to ACL_RULE table

### PR DESCRIPTION
**Pull request by vivekrnv**
#### Why I did it

Add support for user to match on TUNNEL_TERM flag in ACL_RULE table.

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [ ] 202111
- [ ] 202205
- [ ] 202211
- [ ] 202305

#### Tested branch (Please provide the tested image version)

- [ ] 
- [ ]

### CODE REVIEW

**Review by dgsudharsan — CHANGES_REQUESTED** [review]
Please update sample_config_db.json as well as Configuration.md

**Comment by vivekrnv** [comment]
@dgsudharsan Updated the sample_config_db.json

**Comment by dgsudharsan** [comment]
> @dgsudharsan Updated the sample_config_db.json

Can you please update Configuration.md as well?

**Comment by vivekrnv** [comment]
Missed, updated

**Review by dgsudharsan — APPROVED** [review]

**Pull request closed without merging**
